version: '3.8'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - app-network

  backend-test:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: pytest
    environment:
      - FLASK_ENV=testing
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  frontend-test:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: builder
    command: npm run test
    networks:
      - app-network

networks:
  app-network:
    driver: bridge